[mypy]
python_version = 3.13
strict = True

# Ignore FastAPI / framework noise
[mypy-app.routes.*]
ignore_errors = True

[mypy-app.core.*]
ignore_errors = True

[mypy-app.factory]
ignore_errors = True

[mypy-faiss]
ignore_missing_imports = True

[mypy-faiss.*]
ignore_missing_imports = True